#!/usr/bin/env python3
import os
import shutil
import json
import sys

with open('./build.config.json') as json_file:
    meta_json_data = json.load(json_file)
print(json.dumps(meta_json_data, ensure_ascii=False, indent=4))

if len(sys.argv) >= 2:
    configFile = json.load(open(sys.argv[1], 'r'))
    print(json.dumps(configFile, ensure_ascii=False, indent=4))